### ISSUE TITLE
Stack storage allocators are non-conformant

### ISSUE THREAD

**Issue by dimztimz** [hosseinmoein/Cougar#2]
If you carefully read the requirements for C++ allocator you should conclude that an conforming allocator can not keep the memory within itself. If it keeps it inside it, then what happens if you move the allocator object? What happens if you copy it?

So, an allocator object either has no data at all in it like std::allocator, or it should have some pointer to the memory it serves.

**Comment by hosseinmoein** [comment]
You are correct. With that one exception, they are conformant :-)
The user should know that fixed size static or stack memory cannot be moved or copyed.

BTW, the aligned allocator doesn't have this problem.

**Comment by dimztimz** [comment]
The static storage should be conformant because the memory is not part of the object.

> The user should know that fixed size static or stack memory cannot be moved or copyed.

No, that is not correct. There is [strict requirement](https://en.cppreference.com/w/cpp/named_req/Allocator) that a C++ allocator must be copyable and movable. It is not a documentation issue, it is correctness issue. You can not make assumptions how the container will use your allocator.
